### ISSUE TITLE
Add Statistical Areas as attribute to spatial layers

### ISSUE THREAD

**Issue by Maschette** [ccamlr/CCAMLRGIS#40]
Hi, 
It would be super useful if CCAMLR could add the parent statistical area to all the data layers that are subsets of them as attributes.
So examples would be SSRU,  SSMU, Research Blocks, MPAs, Other Management areas ect. 

This would make it much easier to subset the layers to a specific region.

**Comment by sthanassekos** [comment]
Hi,
This is something that will definitely happen in the future - it is in the 5 year Strategic plan. It will unfortunately take a while because it is part of a big overhaul of our online GIS (https://gis.ccamlr.org/) from which the CCAMLRGIS package downloads spatial objects.
In the meantime, some 'parenting' has been manually embedded in the spatial objects dataframes. For instance, these should match:
load_SSRUs()$GAR_Parent_ID
and
load_ASDs()$GAR_ID

If they don't, I would suggest using string matching between "GAR_x_Label" across spatial objects.
Sorry for the inconvenience.

**Comment by mdsumner** [comment]
can't we do this by spatial query between layers?  if @Maschette you can give an example of two layers, I'll do the sf to identify them (or am I missing something)

but happy to help with string matching also, maybe we can contribute back here as a doc
